version: '3.7'

x-defaults: &defaults
    image: sentry:9.1.2
    restart: unless-stopped
    environment:
        SENTRY_SECRET_KEY: ${SENTRY_SECRET_KEY}
        SENTRY_USE_SSL: '1'
        SENTRY_MEMCACHED_HOST: memcached
        SENTRY_REDIS_HOST: redis
        SENTRY_SERVER_EMAIL: 'sentry@automagistre.ru'
        SENTRY_POSTGRES_HOST: postgres
        SENTRY_DB_NAME: db
        SENTRY_DB_USER: db
        SENTRY_DB_PASSWORD: ${DB_PASSWORD}
        SENTRY_EMAIL_HOST: smtp.mailgun.org
        SENTRY_EMAIL_PORT: 587
        SENTRY_EMAIL_USER: ${EMAIL_USER}
        SENTRY_EMAIL_PASSWORD: ${EMAIL_PASSWORD}
        SENTRY_EMAIL_USE_TLS: '1'
    volumes:
        - /opt/sentry/files:/var/lib/sentry/files

services:
    memcached:
        image: memcached:1.6.9-alpine
        restart: unless-stopped

    redis:
        image: redis:6.0.1-alpine
        restart: unless-stopped

    postgres:
        image: postgres:12.2
        restart: unless-stopped
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: db
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - /opt/sentry/postgres:/var/lib/postgresql/data

    web:
        <<: *defaults
        networks:
            - default
            - traefik
        deploy:
            mode: global
            update_config:
                order: stop-first
                failure_action: rollback
                parallelism: 1
                delay: 5s
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.automagistre-sentry.rule=Host(`sentry.automagistre.ru`)"
                - "traefik.http.routers.automagistre-sentry.entrypoints=websecure"
                - "traefik.http.routers.automagistre-sentry.tls=true"
                - "traefik.http.routers.automagistre-sentry.tls.certresolver=leresolver"
                - "traefik.http.services.automagistre-sentry-service.loadbalancer.server.port=9000"
                - "traefik.http.services.automagistre-sentry-service.loadbalancer.server.scheme=http"

    cron:
        <<: *defaults
        command: run cron

    worker:
        <<: *defaults
        command: run worker

    migration:
        <<: *defaults
        command: sentry upgrade
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: none

networks:
    default:
        driver: overlay
        name: sentry
    traefik:
        external: true
        name: traefik
